---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip3 install --upgrade pip pip-tools
  - pip-sync requirements.txt requirements-dev.txt
script:
  - cookiecutter --config-file .example-cookiecutterrc --output-dir $HOME
