---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip3 install ansible molecule docker
script:
  - ansible --version
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
