---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos7
    box: mrlesmithjr/centos7
  - name: centos8
    box: mrlesmithjr/centos8
  - name: debian9
    box: mrlesmithjr/stretch64
  - name: debian10
    box: mrlesmithjr/buster64
  - name: ubuntu1604
    box: mrlesmithjr/xenial64
  - name: ubuntu1804
    box: mrlesmithjr/bionic64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
