---
name: Cookiecutter Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync requirements.txt requirements-dev.txt
      - name: Test with cookiecutter
        run: |
          cookiecutter --config-file .example-cookiecutterrc --no-input --output-dir $HOME .
